(function(){var u,r,o,p;if(typeof console==="undefined"||console===null)console={log:function(){}};var i={xmlsafe:!1,compress:function(a){for(var b=[],g=i.xmlsafe?5:0,e=0;e<256;e++)b[String.fromCharCode(e)]=e;i.xmlsafe&&(b["<"]=256,b[">"]=257,b["&"]=258,b['"']=259,b["'"]=260);for(var d="",a=a.split(""),j=a.length,g=256+g,f="",e=0;e<=j;e++){var c=a[e];b[f+c]!==void 0?f+=c:(d+=String.fromCharCode(b[f]),b[f+c]=g,g++,f=c)}return d},decompress:function(a){for(var b=[],g=i.xmlsafe?5:0,e=0;e<256;e++){var d=
String.fromCharCode(e);b[e]=d}i.xmlsafe&&(b[256]="<",b[257]=">",b[258]="&",b[259]='"',b[260]="'");for(var d=a.split("").length,j=256+g,f="",c="",l="",e=0;e<d;e++){var c=a.charCodeAt(e),h=b[c];f==""?(f=h,l+=h):c<=255+g?(l+=h,c=f+h,b[j]=c,j++,f=h):(c=b[c],c==void 0&&(c=f+f.slice(0,1)),l+=c,b[j]=f+c.slice(0,1),j++,f=c)}return l}};u=function(a){a=atob(a);a=unescape(a);a=i.decompress(a);return JSON.parse(a)};p=function(a){a=JSON.stringify(a);a=i.compress(a);a=escape(a);return btoa(a)};r={};o=function(a,
b){var g;r[a]=b;g=p(r);return $("#share-link").attr("href","#"+g)};$(document).ready(function(){var a,b,g,e,d,j,f,c,l,h,i,q,m,n,s,p,t;j={haml:'%h1 Hello, world!\n\n%p\n    Donec id elit non mi porta gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.\n\n%img{ src: "http://code.alecperkins.net/projector/images/cyan-small.jpg" }',sass:"p\n  :font-family Helvetica, Arial, sans-serif\n  :line-height 170%\n\nimg\n  :border 3px solid ccc\n  :border-radius 8px\n  :background f4f4f4\n  :padding 10px\n  &.selected\n    :border-color red",
coffee:"img = $('img')\nimg.bind 'click', ->\n    img.toggleClass 'selected'",has_jquery:!0,has_underscore:!1};c=null;d=window.location.hash;if((d!=null?d.length:void 0)>1){d=d.substring(1);try{c=u(d)}catch(v){console.log(v),alert("Invalid data in URL hash. Ignoring...")}c!=null&&confirm("Loading Padhacker data from hash will erase current project. Continue?")?window.location.hash="":c=null}$(".tabs li").bind("click",function(k){var a;$("textarea").hide();$(".tabs li.selected").removeClass("selected");
a=$(k.currentTarget).attr("name");$(k.currentTarget).addClass("selected");return $("#"+a).show()});e="";g=function(){var k;k=$("#sass").val();localStorage.setItem("sass",k);o("sass",k);try{return e=sass.render(k),console.log(""+new Date+" - compiled Sass"),h()}catch(a){return console.log(a)}};$("#sass").bind("keyup",function(k){var a;if(!(37<=(a=k.which)&&a<=40))return g()});f="";b=function(){var a;a=$("#haml").val();localStorage.setItem("haml",a);o("haml",a);try{return f=Haml(a)({}),console.log(""+
new Date+" - compiled Haml"),h()}catch(b){return console.log(b)}};$("#haml").bind("keyup",function(a){var c;if(!(37<=(c=a.which)&&c<=40))return b()});l="";a=function(){var a;a=$("#coffee").val();localStorage.setItem("coffee",a);o("coffee",a);try{return l=CoffeeScript.compile(a,{bare:!0}),console.log(""+new Date+" - compiled"),h()}catch(b){return console.log(b)}};$("#coffee").bind("keyup",function(b){var c;if(!(37<=(c=b.which)&&c<=40))return a()});n=m=!1;$("#jquery").bind("click",function(){m=!m;localStorage.setItem("has_jquery",
m);o("has_jquery",m);return h()});$("#underscore").bind("click",function(){n=!n;localStorage.setItem("has_underscore",n);o("has_underscore",n);return h()});$("textarea").bind("keydown",function(a){if(a.which===9)return a.preventDefault(),a=this.selectionStart,this.value=this.value.substring(0,a)+"  "+this.value.substring(a),this.selectionStart=a+2,this.selectionEnd=a+2});i=null;h=function(a){a==null&&(a=!1);i==null&&(console.log(a),i=setTimeout(function(){var a,b;a="<style>"+e+"</style>";m&&(a+='<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/1.6.2/jquery.min.js"><\/script>');
n&&(a+='<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.1.7/underscore-min.js"><\/script>');a+=""+f;a+="<script>"+l+"<\/script>";b=$("iframe")[0].contentWindow.document;b.open();b.write(a);b.close();return i=null},500))};$(".tabs li").first().trigger("click");$("#develop").splitter();if(c!=null)d=c;else{d=j;if(localStorage.getItem("has_jquery")!=null)d.has_jquery=localStorage.getItem("has_jquery")==="true";if(localStorage.getItem("has_underscore")!=null)d.has_underscore=
localStorage.getItem("has_underscore")==="true"}t=["coffee","sass","haml"];s=0;for(p=t.length;s<p;s++)q=t[s],c==null&&(j=localStorage.getItem(q))&&(d[q]=j),$("textarea#"+q).html(d[q]);m=d.has_jquery;$("#jquery").attr("checked",m);n=d.has_underscore;$("#underscore").attr("checked",n);r=d;a();g();b();return h(!0)})}).call(this);
